### ISSUE TITLE
Combinable with Supervisor?

### ISSUE THREAD

**Issue by 0x7061** [fvbock/endless#18]
Hey, thanks for this cool package!

Is this anyhow combinable with supervisor? I'm using it for regular restarts, log rotations, and so on. Only downside while deploying is that with supervisor I don't have graceful restarts...

Any experiences with such a stack?

**Comment by fvbock** [comment]
hi @codingrogue,

i am not familiar with supervisor. 

i found this (http://supervisord.org/configuration.html)

```
stopsignal

    The signal used to kill the program when a stop is requested. This can be any of TERM, HUP, INT, QUIT, KILL, USR1, or USR2.

    Default: TERM

    Required: No.

    Introduced: 3.0
```

not sure it works for you to replace the default SIGTERM with SIGHUP... ?

can you specify where/what does not work as expected when using endless with supervisord?

**Comment by 0x7061** [comment]
I see.. I will evaluate it a little more and if I have questions I'll come back. Thanks so far!

**Comment by hetiansu5** [comment]
it doesnt works for replacing the default SIGTERM with SIGHUP.  when it forked a child process, it may losed the controlled by supervisor。
