### ISSUE TITLE
undefined on import...

### ISSUE THREAD

**Issue by steviesama** [fvbock/endless#31]
`../github.com/fvbock/endless/endless.go:380: srv.SetKeepAlivesEnabled undefined (type *endlessServer has no field or method SetKeepAlivesEnabled)`

When I used go get to get this.

**Comment by fvbock** [comment]
hi @steviesama 

what go version are you running?

**Comment by fvbock** [comment]
i had a quick check and it seems this happens pre golang 1.3?
