### ISSUE TITLE
singalhooks callback function parameter

### ISSUE THREAD

**Issue by wanghe4096** [fvbock/endless#32]
```
server.SignalHooks[endless.PRE_SIGNAL][syscall.SIGUSR1],
    a.Logger.Rotate)
```

func Rotate(conf *toml.TomlTree) {
.....
}

How i do?

**Comment by fvbock** [comment]
hi @wanghe4096 

you can't. signal hooks are `map[int]map[os.Signal][]func()`...

but maybe you can do something like this?

```
func Rotate() {
  conf := os.Getenv("APP_CONFIG")
  ...
}
```

**Comment by wanghe4096** [comment]
thank you
