### ISSUE TITLE
why sleep 1 second in your multi-port example?

### ISSUE THREAD

**Issue by bruceauyeung** [fvbock/endless#33]
https://github.com/fvbock/endless/blob/master/examples/multi_port.go

it sleeps 1 second before `endless.ListenAndServe` in the first goroutine. why ?

**Comment by fvbock** [comment]
i can't remember any more - probably wanted to have the first routine serve later than the second to test something... `¯\_(ツ)_/¯`

anyways: it's not required or serves any function to get multiple servers running and restarting.
