### ISSUE TITLE
FD leak on linux after restart

### ISSUE THREAD

**Issue by kevwan** [fvbock/endless#34]
Hi,

When I use endless, I found the following code cause the memory leak after restart.

```
func main() {
    fd, _ := os.Create("access.log")
    defer fd.Close()
    // start http server
    ...
}
```

After restarting, use lsof to list the open FDs, there are 2 FDs for access.log

Am I using it incorrectly?

Thanks!
Kevin

**Comment by geekfghuang** [comment]
After reading your question I had the same concern about FD leak after restart, so I tested it as follows:
```go
func main() {
	gin.DisableConsoleColor()
	f, _ := os.Create("gin.log")
	gin.DefaultWriter = io.MultiWriter(f)
	router := gin.Default()

	router.GET("/geek", func(c *gin.Context) {
		c.JSON(http.StatusOK, "hello geekfghuang")
	})
	endless.ListenAndServe(":8080", router)
}
```
Before kill -SIGHUP 886:
localhost:~ $ lsof | grep gin.log
demo      886 geekfghuang    3u      REG                1,2       172 1867443 gin.log
tail      896 geekfghuang    3r      REG                1,2       172 1867443 gin.log

After kill -SIGHUP 886:
localhost:~ $ lsof | grep gin.log
tail       896 geekfghuang    3r      REG                1,2       602 1867443 gin.log
demo       927 geekfghuang    4u      REG                1,2       602 1867443 gin.log

So, everything is ok!
