### ISSUE TITLE
Running with a process manager

### ISSUE THREAD

**Issue by jpillora** [fvbock/endless#4]
On restart, the program forks a new copy and closes the old copy, leaving the new one parentless/daemonized. How would you use this with init, upstart, systemd and others? If you can't, what do you do about crashes - restarts and reporting, and also logging?

**Comment by fvbock** [comment]
for init and friends we'd need a pidfile... should be easy to add as an option.

i am not sure what you mean by reporting, but monitoring/crash recovery would be outside the scope of this library ... but i guess your point is that you'd need to be able to use init/systemd etc. in order to take care of that right?

would adding a pidfile option solve your problems or do you need something else?

**Comment by jpillora** [comment]
Sorry, abit slow with the reply. I'm in the planning phase of an app which needs to be continuously deployed and it would be nice to have it managed by init/systemd. I've always run programs in the foreground when under a process manager, though now I look into it there's a `forking` process type in systemd, which uses pidfiles so yes, at this point, it looks like a pidfile option is that would be required

**Comment by importnil** [comment]
@jpillora please can you provide an example of your systemd service unit file? I want to use endless with systemd as well, and something like systemd restart goapp doesn't currently do graceful restart for my app...

**Comment by fzerorubigd** [comment]
systemd forking can not handle multiple restart.

for the first time, systemd wait for the first fork (you should fork once! it has some workaround, simply send yourself a HUP or something similar) but the next time (when you send a signal for a child process) then systemd mark the process as dead. 

For that sort of things, I use https://github.com/amscanne/huptime .

**Comment by spaiz** [comment]
Hi. Any updates? Is there any working way to use endless's graceful restarts with systemd?

**Comment by jpillora** [comment]
I ended up resolving this by writing a new Go package https://github.com/jpillora/overseer
