### ISSUE TITLE
Lower level API

### ISSUE THREAD

**Issue by valpackett** [fvbock/endless#8]
This library only provides public API for `http.Handler`s and not `net.Listener`s :-(
`endlessListener` is private for some reason.
Please make the TCP-level API available!

**Comment by fvbock** [comment]
hi!

the server has access to the `endlessListener` (https://github.com/fvbock/endless/blob/master/endless.go#l65)- but that's not what you need right?

you're asking to make the `endlessListener` into an `EndlessListener`?

**Comment by valpackett** [comment]
Yep. I'm using `net.Listen` in my programs directly, so I need the TCP listener.

**Comment by fvbock** [comment]
i am sorry i havn't done anything on this one yet. did you make a fork and make the changes you want?

**Comment by valpackett** [comment]
Ah, nope. It's not really a priority for me right now.

**Comment by stevenh** [comment]
Addressed by: https://github.com/fvbock/endless/pull/19
