### ISSUE TITLE
endless takes over param handling

### ISSUE THREAD

**Issue by ghost** [fvbock/endless#9]
Expected behavior: endless to append whatever runtime args it needs, but preserve the application command line params.

Actual behavior: endless takes over the command line params, and treats all application params as illegal

What's most curious is that args required by the main app are **still** considered required, even though providing them is disallowed by endless. 

``` bash
1074)internationalsos/riskratings % ./rr -h
Usage of ./rr:
  -continue=false: Dummy -- needed by endless
  -debug=false: Enable debugging
  -pass="": Password
  -port=":8080": Listen port
  -refresh=10: Cache refresh time, in minutes
  -uri="******************": URI of data source
  -user="": Username
1075)internationalsos/riskratings % ./rr
Password is required
Usage of ./rr:
  -continue=false: Dummy -- needed by endless
  -debug=false: Enable debugging
  -pass="": Password
  -port=":8080": Listen port
  -refresh=10: Cache refresh time, in minutes
  -uri="******************": URI of data source
  -user="": Username
1076)internationalsos/riskratings % ./rr -pass xyz -user abc -port :8123
2015/06/29 22:33:58 start listening on localhost:8123
flag provided but not defined: -pass
Usage of ./rr:
  -continue=false: listen on open fd (after forking)
  -socketorder="": previous initialization order - used when more than one listener was started
```

**Comment by fvbock** [comment]
i believe this is due to when/where/how you call `flag.Parse()`  

endless allows other flags to be defined,  preserves them, and appends its own at the end.

have a look here: https://gist.github.com/fvbock/855a980deed441cc31cd

if you compile and run that:

```
$ go build -o flags flags.go
$ ./flags -paramA pValA -paramB
2015/06/30 14:55:15 Got passed: [-paramA pValA -paramB]  # this is from os.Args[1:]
2015/06/30 14:55:15 paramA pValA
2015/06/30 14:55:15 paramB true
2015/06/30 14:55:16 22335 localhost:4242
```

Now send SIGHUP

```
$ kill -1 22335

2015/06/30 14:55:30 22335 Received SIGHUP. forking.
2015/06/30 14:55:30 Got passed: [-paramA pValA -paramB -continue]
2015/06/30 14:55:30 paramA pValA
2015/06/30 14:55:30 paramB true
2015/06/30 14:55:30 22351 localhost:4242
```

the original parameters are kept and endless appends it's own parameters at the end.

does this help?

**Comment by ghost** [comment]
When I posted the issue, it briefly crossed my mind that it might be a library interaction, but the lateness of the hour left me too lazy to test it.

It turns out that this is an interaction between endless and my favorite drop-in flag parsing library by [namsral](http://github.com/namsral/flag).  Try [this code](http://play.golang.org/p/5ShQcHPmAv) and the pattern fails.  Use the Go standard flag library and it succeeds.

I don't yet know in which library the issue lies, so I'll withdraw the ticket until I can investigate further.

Thanks for the speedy and civil response.

**Comment by serussell** [comment]
FYI https://github.com/namsral/flag/issues/3

**Comment by ghost** [comment]
Really closed. This is not an endless issue.  For the curious, this can be followed in [namsral/flag](https://github.com/namsral/flag/issues/3).
